Add React Todo App
Jawad-Nazari/React-Todo-App pull request #2
Opened 2023-05-30 20:29 UTC by Jawad-Nazari

### In this PR, I did the following:

- Create react app using vite
- Use GitFlow to introduce new features 💡
- Add components
- Add add-task, edit-task, and delete-task functionalities
- Setup linters 🐛
- Add bable to transpile modern JavaScript syntax into code that can run in all environments when writing React components

2023-06-26 18:29 UTC, ab-noori requested changes
# Status: Changes Requested ♻️ 
### Hi @Jawad-Nazari  :wave:,

Good job thus far!
There are a few minor issues; I believe it would be better to address them before proceeding to the next phase of your project. However, please remember that you have done an exceptional job and you are nearly finished! 🥇 

![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)
## Highlights 👌
- Amazing work you have done so far 👍 
- GitHub flow followed 👌
- Branch name is descriptive 💯 
- Linter set up well and checks pass 🟢
- PR description is descriptive 📝
- Commit messages are meaningful 📝
- .gitignore used to ignore unnecessary files 📁
- You have implemented all requirements until this point 💯 .
- JavaScript best practices followed 👍 
- DRY, KISS, and YAGNI rules followed👍 
- HTML & CSS best practices followed👍 

## Required Changes ♻️
 _Please check the following comments with **`[REQUIRED]`** badges._

## Optional suggestions
_Every comment with the **`[OPTIONAL]`** prefix won't be required to implement. However, I strongly recommend you consider them as they can improve your code. Some of them will improve your application._

## Cheers and happy coding!👏👏👏

2023-06-26 18:29 UTC, ab-noori commented on README.md
- [ ] **`[REQUIRED]`** It appears that you have designed the user interface (UI) of your project quite well 💯 . It would be better to include a screenshot of the UI in the project's documentation ✔️. Therefore, please add a screenshot from your project at the beginning of the README file, before the table of contents 👇 . 
![image](https://github.com/Jawad-Nazari/React-Todo-App/assets/111179533/35e493dc-21b6-40d9-a687-df93dce5cf0b)

2023-06-26 18:29 UTC, ab-noori commented on README.md
- [ ] **`[OPTIONAL]`** I have noticed some unnecessary comments in your codebase. It would be better to keep our codebase as clean as possible. Therefore, kindly remove any unnecessary comments from your codebase 👇 .
![image](https://github.com/Jawad-Nazari/React-Todo-App/assets/111179533/a6e8fe86-15d2-41b4-b62f-07f3b960d07a).

- [ ] **`[OPTIONAL]`** It is also a good idea if your project has demo links. you deploy it on Gh-pages or on render.com.

2023-06-27 05:04 UTC, Jawad-Nazari commented on README.md
Hi @ab-noori 
Thanks for your time and for reviewing my code, I have applied the required changes.

2023-06-27 06:18 UTC, ab-noori approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
### Hi @Jawad-Nazari :wave: ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)

## Highlights
- You have done amazing work so far! 👍
- You have successfully implemented all the requirements requested in the previous review ✔ 

## Cheers and happy coding!👏👏👏

2023-06-27 07:10 UTC, merged